server:
  port: 8801
  
spring:
  application:
    name: departamento
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8800/eureka
   